# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'corne nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_RGB_UNDERGLOW=y\nCONFIG_WS2812_STRIP=y\nCONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3\nCONFIG_ZMK_RGB_UNDERGLOW_SPD_START=1\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y\nCONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=30\nCONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=40000"]'
      #kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_RGB_UNDERGLOW=y\nCONFIG_WS2812_STRIP=y\nCONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3\nCONFIG_ZMK_RGB_UNDERGLOW_SPD_START=1\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y\nCONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=30\nCONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y"]'
