# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'stefan corne nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      #shield: '["corne_left","corne_right"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view","settings_reset"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_POINTING=y","CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_POINTING=y\nCONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y",""]'
      #kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_RGB_UNDERGLOW=y\nCONFIG_WS2812_STRIP=y\nCONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3\nCONFIG_ZMK_RGB_UNDERGLOW_SPD_START=1\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y\nCONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=30\nCONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y"]'
     
